// seeds/02_reservations.js

export const seed = async (knex) => {
  // Deletes ALL existing entries
  await knex("reservations").del();

  // Fetch all user IDs from the users table
  const users = await knex("users").select("id");

  // Inserts seed entries with time in 12-hour format
  const reservations = [
    {
      user_id: users[0].id,
      name: "John Doe",
      date: "2024-08-20",
      time: "07:00 PM",
      party_size: 4,
      status: "confirmed",
      // tables_required: 2,
    },
    {
      user_id: users[0].id,
      name: "John Doe",
      date: "2024-08-21",
      time: "08:00 PM",
      party_size: 2,
      status: "pending",
      // tables_required: 1,
    },
    {
      user_id: users[1].id,
      name: "Jane Smith",
      date: "2024-08-22",
      time: "07:00 PM",
      party_size: 3,
      status: "confirmed",
      // tables_required: 2,
    },
    {
      user_id: users[1].id,
      name: "Jane Smith",
      date: "2024-08-23",
      time: "06:30 PM",
      party_size: 6,
      status: "canceled",
      // tables_required: 3,
    },
    {
      user_id: users[2].id,
      name: "Alice Johnson",
      date: "2024-08-24",
      time: "07:00 PM",
      party_size: 4,
      status: "confirmed",
      // tables_required: 2,
    },
    {
      user_id: users[2].id,
      name: "Alice Johnson",
      date: "2024-08-25",
      time: "08:00 PM",
      party_size: 2,
      status: "pending",
      // tables_required: 1,
    },
    {
      user_id: users[3].id,
      name: "Bob Brown",
      date: "2024-08-26",
      time: "06:00 PM",
      party_size: 5,
      status: "confirmed",
      // tables_required: 3,
    },
    {
      user_id: users[3].id,
      name: "Bob Brown",
      date: "2024-08-27",
      time: "09:00 PM",
      party_size: 2,
      status: "pending",
      // tables_required: 1,
    },
    {
      user_id: users[4].id,
      name: "Carol White",
      date: "2024-08-28",
      time: "05:30 PM",
      party_size: 4,
      status: "confirmed",
      // tables_required: 2,
    },
    {
      user_id: users[4].id,
      name: "Carol White",
      date: "2024-08-29",
      time: "08:00 PM",
      party_size: 6,
      status: "confirmed",
      // tables_required: 3,
    },
    {
      user_id: users[5].id,
      name: "Dave Black",
      date: "2024-08-20",
      time: "06:00 PM",
      party_size: 4,
      status: "confirmed",
      // tables_required: 2,
    },
    {
      user_id: users[5].id,
      name: "Dave Black",
      date: "2024-08-21",
      time: "07:00 PM",
      party_size: 2,
      status: "canceled",
      // tables_required: 1,
    },
    {
      user_id: users[6].id,
      name: "Eve Green",
      date: "2024-08-22",
      time: "06:30 PM",
      party_size: 3,
      status: "confirmed",
      // tables_required: 2,
    },
    {
      user_id: users[6].id,
      name: "Eve Green",
      date: "2024-08-23",
      time: "08:00 PM",
      party_size: 5,
      status: "pending",
      // tables_required: 3,
    },
    {
      user_id: users[7].id,
      name: "Frank Blue",
      date: "2024-08-24",
      time: "07:30 PM",
      party_size: 4,
      status: "confirmed",
      // tables_required: 2,
    },
    {
      user_id: users[7].id,
      name: "Frank Blue",
      date: "2024-08-25",
      time: "09:00 PM",
      party_size: 2,
      status: "canceled",
      // tables_required: 1,
    },
    {
      user_id: users[8].id,
      name: "Grace Red",
      date: "2024-08-26",
      time: "05:30 PM",
      party_size: 3,
      status: "confirmed",
      // tables_required: 2,
    },
    {
      user_id: users[8].id,
      name: "Grace Red",
      date: "2024-08-27",
      time: "07:00 PM",
      party_size: 4,
      status: "pending",
      // tables_required: 2,
    },
    {
      user_id: users[9].id,
      name: "Hank Yellow",
      date: "2024-08-28",
      time: "06:00 PM",
      party_size: 5,
      status: "confirmed",
      // tables_required: 3,
    },
    {
      user_id: users[9].id,
      name: "Hank Yellow",
      date: "2024-08-29",
      time: "08:00 PM",
      party_size: 6,
      status: "confirmed",
      // tables_required: 3,
    },
  ];

  await knex("reservations").insert(reservations);
};
